services:
  - type: web
    name: drama-adflow-api
    env: python
    buildCommand: pip install -r api/requirements.txt
    startCommand: gunicorn api.server:app --worker-class sync --workers 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DASHSCOPE_API_KEY
        sync: false
